/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vizualização;

import controle.DAO.ClienteDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.PessoaFisica;
import modelo.ValidaCPF;

/**
 *
 * @author 381121742018.1
 */
public class CadastroPessoaFisica extends javax.swing.JFrame {
    public void limparCampos(){
    jtfNomePessoa.setText("");
    jtfNomeSocial.setText("");
    jtfCpf.setText("");
    jtfCep.setText("");
    jtfNum.setText("");
    jtfCompl.setText("");
    
    }
    
    public CadastroPessoaFisica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNomePessoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfCep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfCompl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbtcadastrar = new javax.swing.JButton();
        jbfcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nome completo:");

        jtfNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomePessoaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome social:");

        jLabel3.setText("CPF:");

        jLabel4.setText("CEP:");

        jLabel5.setText("Número");

        jLabel6.setText("Complemento:");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setText("Cadastro pessoa física");

        jbtcadastrar.setText("Cadastrar");
        jbtcadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtcadastrarMouseClicked(evt);
            }
        });
        jbtcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcadastrarActionPerformed(evt);
            }
        });

        jbfcancelar.setText("Cancelar");
        jbfcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbfcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtcadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNomePessoa)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtfNomeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfCpf))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfNum))
                                .addComponent(jtfCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfNomeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jtfNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtcadastrar)
                    .addComponent(jbfcancelar))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomePessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomePessoaActionPerformed

    private void jbtcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcadastrarActionPerformed
        PessoaFisica pf = new PessoaFisica();
        
        pf.setNomePessoa(jtfNomePessoa.getText());
        pf.setNomeSocial(jtfNomeSocial.getText());
        pf.setCep(jtfCep.getText());
        pf.setNum(jtfNum.getText());
        pf.setComplemento(jtfCompl.getText());
        
        pf.setCpf(jtfCpf.getText());
        
        ValidaCPF valid = new ValidaCPF();
        if(valid.validarC(pf.getCpf())== true){
        ClienteDAO cdao = new ClienteDAO();
        
            try {
                cdao.inserirClienteF(pf);
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroPessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
                
                
            
               
            }
		}else
                     JOptionPane.showMessageDialog(null,"CPF invalido");
			System.out.println("CPF Invalido");

        
    }//GEN-LAST:event_jbtcadastrarActionPerformed

    private void jbtcadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtcadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtcadastrarMouseClicked

    private void jbfcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfcancelarActionPerformed
        limparCampos();
        dispose();
    }//GEN-LAST:event_jbfcancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbfcancelar;
    private javax.swing.JButton jbtcadastrar;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCompl;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfNomePessoa;
    private javax.swing.JTextField jtfNomeSocial;
    private javax.swing.JTextField jtfNum;
    // End of variables declaration//GEN-END:variables

}